Add config to mark server as read-only
altugbakan/rs-tftpd pull request #2
Opened 2023-07-16 15:28 UTC by Foorack

This PR adds a new config option to mark the server as read-only. When this option is set, the server will not allow any write operations. README and documentation have been updated to include this new option. It can be toggled with `--read-only` or `-r` for short. Added similar tests to the existing ones to ensure that the config flag works as expected.

2023-07-16 18:25 UTC, altugbakan requested changes
Thank you for adding this option, looks amazing overall!

2023-07-16 18:25 UTC, altugbakan commented on README.md
> +tftpd -i 0.0.0.0 -p 1234 -d "/home/user/tftp" --read-only
Hey, thank you a lot for your addition, just a nitpick, can you use the short flag for the read-only option for this example?

```suggestion
tftpd -i 0.0.0.0 -p 1234 -d "/home/user/tftp" -r
```

2023-07-17 08:09 UTC, Foorack commented
@altugbakan Thanks, suggestion applied!

2023-07-17 09:21 UTC, altugbakan approved these changes
LGTM

2023-07-17 09:21 UTC, merged